# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d19afd3f0ad1825cb260279c4ecb78df10de517686b947c2ff4bd2e5f2c53c13fe3bdb6ec2686062a01780f9587bf5dd54718b546aef3769cfa61e49581fd634

test:
  secret_key_base: 1ab57044449505cd96af15210287d989010e8f61e30670cd468f1a2d9c38d4b1ef8f4bc38e41b76b253d9c5fd32a1cc504be2ac12ad63260f2509b1203b93ed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
