# http://about.travis-ci.org/docs/user/build-configuration/
language: ruby

bundler_args: '--without production'

script: CODECLIMATE_REPO_TOKEN=7d6b988f58234bf1560305412d10d9530902beebdbe2fb938b6a934f1d352578 bundle exec rake

before_install:
  - "cat /etc/timezone"
  - "grep -i processor /proc/cpuinfo | wc -l"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "gem install bundler --pre"
  - "bundle -v"

before_script:
    - "bundle exec rake travis:before_script"
services:
    - mongodb

rvm:
  - 2.0.0
  - 2.1.0
